version: '3.7'

services:
  crawler:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - URL=https://pastebin.com
      - published_time_threshold=120

